import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu_Sans } from "next/font/google";

const UbuntuSans = Ubuntu_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${UbuntuSans.className} bg-white text-gray-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
